language: node_js
node_js:
- '10'
services:
  - postgresql
before_script:
  - psql -c 'create database jobly_test;' -U postgres
  - psql jobly_test < dataTest.sql
install:
  - npm install jest
script:
  - npm test